// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/get-ad-account.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        )?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("Supabase publishable key is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("Missing verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/meta.ts
var GRAPH_VERSION = "v21.0";
var AD_ACCOUNT_ID = "act_336967666";
async function requireAdmin(ctx) {
  if (!ctx.isAuthenticated?.() || !ctx.getUserId?.()) {
    return "Not authenticated.";
  }
  try {
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("is_mcp_admin", {
      _user_id: ctx.getUserId()
    });
    if (error || data !== true) {
      return "Forbidden: account is not an Automind MCP admin.";
    }
    return null;
  } catch {
    return "Authorization check failed.";
  }
}
function errorResult(text) {
  return { content: [{ type: "text", text }], isError: true };
}
function jsonResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload) }],
    structuredContent: payload
  };
}
async function graphGet(path, params) {
  const token = runtimeEnv("META_SYSTEM_USER_TOKEN");
  if (!token) return { data: null, status: 500 };
  const url = new URL(`https://graph.facebook.com/${GRAPH_VERSION}/${path}`);
  for (const [k, v] of Object.entries(params)) url.searchParams.set(k, v);
  const resp = await fetch(url.toString(), {
    method: "GET",
    headers: { Authorization: `Bearer ${token}` }
  });
  if (!resp.ok) {
    console.error("meta graph request failed", resp.status);
    return { data: null, status: resp.status };
  }
  return { data: await resp.json(), status: 200 };
}
function upstreamError(status) {
  return errorResult(
    status === 500 ? "Meta credentials are not configured on the server." : status === 403 ? "Meta API refused the request (permission denied). The server token may lack ads_management." : status === 400 ? "Meta API rejected the request (invalid parameters or not allowed for this object)." : `Meta API request failed (status ${status}).`
  );
}

// src/lib/mcp/tools/get-ad-account.ts
var get_ad_account_default = defineTool({
  name: "get_ad_account",
  title: "Get Meta ad account",
  description: "Use this to read basic status of the Automind Meta ad account. Returns id, name, account_status, currency and timezone_name. Read-only, no inputs.",
  inputSchema: {},
  annotations: {
    readOnlyHint: true,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: true
  },
  handler: async (_input, ctx) => {
    const denied = await requireAdmin(ctx);
    if (denied) return errorResult(denied);
    const res = await graphGet(AD_ACCOUNT_ID, {
      fields: "id,name,account_status,currency,timezone_name"
    });
    if (!res.data) return upstreamError(res.status);
    const d = res.data ?? {};
    return jsonResult({
      id: d.id ?? null,
      name: d.name ?? null,
      account_status: d.account_status ?? null,
      currency: d.currency ?? null,
      timezone_name: d.timezone_name ?? null
    });
  }
});

// src/lib/mcp/tools/list-campaigns.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^4.5.4";
var list_campaigns_default = defineTool2({
  name: "list_campaigns",
  title: "List Meta campaigns",
  description: "Use this to list campaigns in the Automind Meta ad account. Optional 'limit' between 1 and 50 (default 20). Returns id, name, status, effective_status, objective, created_time and updated_time for each campaign. Read-only.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum campaigns to return (1-50, default 20).")
  },
  annotations: {
    readOnlyHint: true,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: true
  },
  handler: async ({ limit }, ctx) => {
    const denied = await requireAdmin(ctx);
    if (denied) return errorResult(denied);
    const bounded = Math.min(Math.max(limit ?? 20, 1), 50);
    const res = await graphGet(`${AD_ACCOUNT_ID}/campaigns`, {
      fields: "id,name,status,effective_status,objective,created_time,updated_time",
      limit: String(bounded)
    });
    if (!res.data) return upstreamError(res.status);
    const rows = Array.isArray(res.data?.data) ? res.data.data : [];
    const campaigns = rows.slice(0, bounded).map((c) => ({
      id: c?.id ?? null,
      name: c?.name ?? null,
      status: c?.status ?? null,
      effective_status: c?.effective_status ?? null,
      objective: c?.objective ?? null,
      created_time: c?.created_time ?? null,
      updated_time: c?.updated_time ?? null
    }));
    return jsonResult({ count: campaigns.length, limit: bounded, campaigns });
  }
});

// src/lib/mcp/tools/get-campaign-insights.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^4.5.4";
var DATE_PRESETS = ["today", "yesterday", "last_7d", "last_14d", "last_30d"];
var METRICS = [
  "spend",
  "impressions",
  "reach",
  "clicks",
  "inline_link_clicks",
  "ctr",
  "cpc",
  "cpm"
];
var get_campaign_insights_default = defineTool3({
  name: "get_campaign_insights",
  title: "Get Meta campaign insights",
  description: "Use this to read performance metrics for one campaign in the Automind Meta ad account. Requires 'campaign_id' (must belong to the account) and 'date_preset' (today, yesterday, last_7d, last_14d, last_30d). Returns spend, impressions, reach, clicks, inline_link_clicks, ctr, cpc, cpm and actions when Meta reports them. Read-only; missing metrics are returned as null and never estimated.",
  inputSchema: {
    campaign_id: z2.string().trim().regex(/^\d{5,25}$/, "campaign_id must be a numeric Meta campaign ID").describe("Numeric Meta campaign ID from list_campaigns."),
    date_preset: z2.enum(DATE_PRESETS).describe("Reporting window: today, yesterday, last_7d, last_14d or last_30d.")
  },
  annotations: {
    readOnlyHint: true,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: true
  },
  handler: async ({ campaign_id, date_preset }, ctx) => {
    const denied = await requireAdmin(ctx);
    if (denied) return errorResult(denied);
    const owner = await graphGet(campaign_id, { fields: "id,name,account_id" });
    if (!owner.data) {
      return owner.status === 400 || owner.status === 404 ? errorResult("Campaign not found.") : upstreamError(owner.status);
    }
    const accountId = owner.data?.account_id ? `act_${owner.data.account_id}` : null;
    if (accountId !== AD_ACCOUNT_ID) {
      return errorResult("Campaign does not belong to the allowed ad account.");
    }
    const res = await graphGet(`${campaign_id}/insights`, {
      fields: [...METRICS, "actions"].join(","),
      date_preset,
      limit: "1"
    });
    if (!res.data) return upstreamError(res.status);
    const row = Array.isArray(res.data?.data) ? res.data.data[0] : void 0;
    if (!row) {
      return jsonResult({
        campaign_id,
        campaign_name: owner.data?.name ?? null,
        date_preset,
        has_data: false,
        metrics: null,
        actions: null
      });
    }
    const metrics = {};
    for (const m of METRICS) metrics[m] = row?.[m] ?? null;
    const actions = Array.isArray(row?.actions) ? row.actions.slice(0, 25).map((a) => ({ action_type: a?.action_type ?? null, value: a?.value ?? null })) : null;
    return jsonResult({
      campaign_id,
      campaign_name: owner.data?.name ?? null,
      date_preset,
      has_data: true,
      metrics,
      actions
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "vkpaugrneyxbqqgkafgl";
var mcp_default = defineMcp({
  name: "automind-ai-agents",
  title: "automind-ai-agents",
  version: "0.1.0",
  instructions: "Private, read-only Automind tools for the Meta ad account act_336967666. Access is limited to Automind admins. Use get_ad_account for account status, list_campaigns to find campaigns, and get_campaign_insights for performance metrics of a single campaign. No write, budget or spend operations are available.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_ad_account_default, list_campaigns_default, get_campaign_insights_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
